---
- hosts: wordpress
  remote_user: leonardo
  become: yes
  tasks:
    - name: "Executa container MySQL"
      docker_container:
        name: db_wordpress
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: minhasenha
    - name: "Executa o container WordPress"
      docker_container:
        name: wordpress
        image: wordpress
        links:
          - "db_wordpress:mysql"
        ports:
          - "8080:8080"